// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datapool.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Holdersnum           int32    `protobuf:"varint,2,opt,name=holdersnum,proto3" json:"holdersnum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *CreateRequest) GetHoldersnum() int32 {
	if m != nil {
		return m.Holdersnum
	}
	return 0
}

type DatapoolInfo struct {
	Datapoolid           string   `protobuf:"bytes,1,opt,name=datapoolid,proto3" json:"datapoolid,omitempty"`
	Ownerid              string   `protobuf:"bytes,2,opt,name=ownerid,proto3" json:"ownerid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatapoolInfo) Reset()         { *m = DatapoolInfo{} }
func (m *DatapoolInfo) String() string { return proto.CompactTextString(m) }
func (*DatapoolInfo) ProtoMessage()    {}
func (*DatapoolInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{1}
}

func (m *DatapoolInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatapoolInfo.Unmarshal(m, b)
}
func (m *DatapoolInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatapoolInfo.Marshal(b, m, deterministic)
}
func (m *DatapoolInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatapoolInfo.Merge(m, src)
}
func (m *DatapoolInfo) XXX_Size() int {
	return xxx_messageInfo_DatapoolInfo.Size(m)
}
func (m *DatapoolInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DatapoolInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DatapoolInfo proto.InternalMessageInfo

func (m *DatapoolInfo) GetDatapoolid() string {
	if m != nil {
		return m.Datapoolid
	}
	return ""
}

func (m *DatapoolInfo) GetOwnerid() string {
	if m != nil {
		return m.Ownerid
	}
	return ""
}

type AddHolderRequest struct {
	Datapoolid           string   `protobuf:"bytes,1,opt,name=datapoolid,proto3" json:"datapoolid,omitempty"`
	Holdersnum           int32    `protobuf:"varint,2,opt,name=holdersnum,proto3" json:"holdersnum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddHolderRequest) Reset()         { *m = AddHolderRequest{} }
func (m *AddHolderRequest) String() string { return proto.CompactTextString(m) }
func (*AddHolderRequest) ProtoMessage()    {}
func (*AddHolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{2}
}

func (m *AddHolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHolderRequest.Unmarshal(m, b)
}
func (m *AddHolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHolderRequest.Marshal(b, m, deterministic)
}
func (m *AddHolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHolderRequest.Merge(m, src)
}
func (m *AddHolderRequest) XXX_Size() int {
	return xxx_messageInfo_AddHolderRequest.Size(m)
}
func (m *AddHolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddHolderRequest proto.InternalMessageInfo

func (m *AddHolderRequest) GetDatapoolid() string {
	if m != nil {
		return m.Datapoolid
	}
	return ""
}

func (m *AddHolderRequest) GetHoldersnum() int32 {
	if m != nil {
		return m.Holdersnum
	}
	return 0
}

type AddHolderResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddHolderResult) Reset()         { *m = AddHolderResult{} }
func (m *AddHolderResult) String() string { return proto.CompactTextString(m) }
func (*AddHolderResult) ProtoMessage()    {}
func (*AddHolderResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{3}
}

func (m *AddHolderResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHolderResult.Unmarshal(m, b)
}
func (m *AddHolderResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHolderResult.Marshal(b, m, deterministic)
}
func (m *AddHolderResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHolderResult.Merge(m, src)
}
func (m *AddHolderResult) XXX_Size() int {
	return xxx_messageInfo_AddHolderResult.Size(m)
}
func (m *AddHolderResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHolderResult.DiscardUnknown(m)
}

var xxx_messageInfo_AddHolderResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterType((*DatapoolInfo)(nil), "pb.DatapoolInfo")
	proto.RegisterType((*AddHolderRequest)(nil), "pb.AddHolderRequest")
	proto.RegisterType((*AddHolderResult)(nil), "pb.AddHolderResult")
}

func init() { proto.RegisterFile("datapool.proto", fileDescriptor_1730072fb3ac63c1) }

var fileDescriptor_1730072fb3ac63c1 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x49, 0x2c, 0x49,
	0x2c, 0xc8, 0xcf, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72,
	0xe7, 0xe2, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe3, 0x62, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0xf2, 0x84, 0xe4, 0xb8, 0xb8, 0x32, 0xf2, 0x73, 0x52, 0x52, 0x8b, 0x8a, 0xf3, 0x4a, 0x73,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x90, 0x44, 0x94, 0x3c, 0xb8, 0x78, 0x5c, 0xa0, 0xc6,
	0x7b, 0xe6, 0xa5, 0xe5, 0x83, 0xd4, 0xc3, 0xac, 0x83, 0x9b, 0x85, 0x24, 0x22, 0x24, 0xc1, 0xc5,
	0x9e, 0x5f, 0x9e, 0x07, 0xb6, 0x88, 0x09, 0x2c, 0x09, 0xe3, 0x2a, 0x05, 0x71, 0x09, 0x38, 0xa6,
	0xa4, 0x78, 0x80, 0x8d, 0x86, 0xb9, 0x8a, 0x90, 0x69, 0x84, 0x5c, 0x27, 0xc8, 0xc5, 0x8f, 0x64,
	0x66, 0x71, 0x69, 0x4e, 0x89, 0x51, 0x1d, 0x17, 0x07, 0xcc, 0xc1, 0x42, 0xe6, 0x5c, 0x7c, 0x90,
	0x50, 0x80, 0x8b, 0x08, 0xea, 0x15, 0x24, 0xe9, 0xa1, 0x84, 0x8c, 0x94, 0x00, 0x48, 0x08, 0xd9,
	0x8f, 0x4a, 0x0c, 0x42, 0x96, 0x5c, 0x5c, 0x70, 0x73, 0x8b, 0x85, 0x44, 0x40, 0x2a, 0xd0, 0xdd,
	0x2e, 0x25, 0x8c, 0x26, 0x0a, 0xb2, 0x5d, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0x09, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x76, 0x39, 0xcd, 0x7c, 0x96, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatapoolClient is the client API for Datapool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatapoolClient interface {
	CreateDatapool(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DatapoolInfo, error)
	AddHolders(ctx context.Context, in *AddHolderRequest, opts ...grpc.CallOption) (*AddHolderResult, error)
}

type datapoolClient struct {
	cc *grpc.ClientConn
}

func NewDatapoolClient(cc *grpc.ClientConn) DatapoolClient {
	return &datapoolClient{cc}
}

func (c *datapoolClient) CreateDatapool(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DatapoolInfo, error) {
	out := new(DatapoolInfo)
	err := c.cc.Invoke(ctx, "/pb.Datapool/CreateDatapool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datapoolClient) AddHolders(ctx context.Context, in *AddHolderRequest, opts ...grpc.CallOption) (*AddHolderResult, error) {
	out := new(AddHolderResult)
	err := c.cc.Invoke(ctx, "/pb.Datapool/AddHolders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatapoolServer is the server API for Datapool service.
type DatapoolServer interface {
	CreateDatapool(context.Context, *CreateRequest) (*DatapoolInfo, error)
	AddHolders(context.Context, *AddHolderRequest) (*AddHolderResult, error)
}

func RegisterDatapoolServer(s *grpc.Server, srv DatapoolServer) {
	s.RegisterService(&_Datapool_serviceDesc, srv)
}

func _Datapool_CreateDatapool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapoolServer).CreateDatapool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Datapool/CreateDatapool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapoolServer).CreateDatapool(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datapool_AddHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapoolServer).AddHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Datapool/AddHolders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapoolServer).AddHolders(ctx, req.(*AddHolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Datapool_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Datapool",
	HandlerType: (*DatapoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDatapool",
			Handler:    _Datapool_CreateDatapool_Handler,
		},
		{
			MethodName: "AddHolders",
			Handler:    _Datapool_AddHolders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datapool.proto",
}
