// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkRequest struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Add                  int32    `protobuf:"varint,2,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkRequest) Reset()         { *m = WorkRequest{} }
func (m *WorkRequest) String() string { return proto.CompactTextString(m) }
func (*WorkRequest) ProtoMessage()    {}
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0}
}

func (m *WorkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkRequest.Unmarshal(m, b)
}
func (m *WorkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkRequest.Marshal(b, m, deterministic)
}
func (m *WorkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkRequest.Merge(m, src)
}
func (m *WorkRequest) XXX_Size() int {
	return xxx_messageInfo_WorkRequest.Size(m)
}
func (m *WorkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkRequest proto.InternalMessageInfo

func (m *WorkRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *WorkRequest) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

type OrderInfo struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	DatabaseMarkleRoot   string   `protobuf:"bytes,2,opt,name=database_markle_root,json=databaseMarkleRoot,proto3" json:"database_markle_root,omitempty"`
	ScriptMarkleRoot     string   `protobuf:"bytes,3,opt,name=script_markle_root,json=scriptMarkleRoot,proto3" json:"script_markle_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{1}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *OrderInfo) GetDatabaseMarkleRoot() string {
	if m != nil {
		return m.DatabaseMarkleRoot
	}
	return ""
}

func (m *OrderInfo) GetScriptMarkleRoot() string {
	if m != nil {
		return m.ScriptMarkleRoot
	}
	return ""
}

type ValidationResult struct {
	DatabaseMarkleRoot   string   `protobuf:"bytes,1,opt,name=database_markle_root,json=databaseMarkleRoot,proto3" json:"database_markle_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResult) Reset()         { *m = ValidationResult{} }
func (m *ValidationResult) String() string { return proto.CompactTextString(m) }
func (*ValidationResult) ProtoMessage()    {}
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{2}
}

func (m *ValidationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResult.Unmarshal(m, b)
}
func (m *ValidationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResult.Marshal(b, m, deterministic)
}
func (m *ValidationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResult.Merge(m, src)
}
func (m *ValidationResult) XXX_Size() int {
	return xxx_messageInfo_ValidationResult.Size(m)
}
func (m *ValidationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResult proto.InternalMessageInfo

func (m *ValidationResult) GetDatabaseMarkleRoot() string {
	if m != nil {
		return m.DatabaseMarkleRoot
	}
	return ""
}

type CommitResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitResult) Reset()         { *m = CommitResult{} }
func (m *CommitResult) String() string { return proto.CompactTextString(m) }
func (*CommitResult) ProtoMessage()    {}
func (*CommitResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{3}
}

func (m *CommitResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResult.Unmarshal(m, b)
}
func (m *CommitResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResult.Marshal(b, m, deterministic)
}
func (m *CommitResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResult.Merge(m, src)
}
func (m *CommitResult) XXX_Size() int {
	return xxx_messageInfo_CommitResult.Size(m)
}
func (m *CommitResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WorkRequest)(nil), "pb.WorkRequest")
	proto.RegisterType((*OrderInfo)(nil), "pb.OrderInfo")
	proto.RegisterType((*ValidationResult)(nil), "pb.ValidationResult")
	proto.RegisterType((*CommitResult)(nil), "pb.CommitResult")
}

func init() { proto.RegisterFile("orders.proto", fileDescriptor_e0f5d4cf0fc9e41b) }

var fileDescriptor_e0f5d4cf0fc9e41b = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x6d, 0xda, 0xef, 0x8b, 0x94, 0x6b, 0x81, 0xe8, 0x54, 0xa1, 0xaa, 0x53, 0xe5, 0xa9, 0x03,
	0x0a, 0x08, 0x06, 0x16, 0xb6, 0xb2, 0x30, 0x20, 0x24, 0x0f, 0x30, 0x56, 0x0e, 0x36, 0x52, 0xd4,
	0xa4, 0x17, 0xce, 0x17, 0x31, 0xf2, 0xd7, 0x91, 0x9d, 0x42, 0x0b, 0x52, 0xb7, 0xbb, 0x7b, 0xcf,
	0xef, 0x9d, 0xdf, 0xc1, 0x84, 0xd8, 0x3a, 0xf6, 0x45, 0xcb, 0x24, 0x84, 0xc3, 0xb6, 0x54, 0xb7,
	0x30, 0x7e, 0x21, 0xde, 0x68, 0xf7, 0xde, 0x39, 0x2f, 0x78, 0x0e, 0x69, 0xe7, 0x1d, 0x57, 0x76,
	0x96, 0x2c, 0x92, 0x65, 0xa6, 0x77, 0x1d, 0xe6, 0x30, 0x32, 0xd6, 0xce, 0x86, 0x8b, 0x64, 0xf9,
	0x5f, 0x87, 0x52, 0x7d, 0x42, 0xf6, 0x14, 0xc4, 0x1e, 0xb6, 0x6f, 0x84, 0x08, 0xff, 0x8c, 0xb5,
	0xbc, 0x7b, 0x14, 0x6b, 0xbc, 0x82, 0xa9, 0x35, 0x62, 0x4a, 0xe3, 0xdd, 0xba, 0x31, 0xbc, 0xa9,
	0xdd, 0x9a, 0x89, 0x24, 0x6a, 0x64, 0x1a, 0xbf, 0xb1, 0xc7, 0x08, 0x69, 0x22, 0xc1, 0x0b, 0x40,
	0xff, 0xca, 0x55, 0x2b, 0xbf, 0xf8, 0xa3, 0xc8, 0xcf, 0x7b, 0x64, 0xcf, 0x56, 0xf7, 0x90, 0x3f,
	0x9b, 0xba, 0xb2, 0x46, 0x2a, 0xda, 0x6a, 0xe7, 0xbb, 0x5a, 0x8e, 0x7a, 0x26, 0xc7, 0x3c, 0xd5,
	0x29, 0x4c, 0x56, 0xd4, 0x34, 0x95, 0xf4, 0x0a, 0xd7, 0x1f, 0x90, 0xc6, 0x6f, 0x79, 0xbc, 0x84,
	0xf1, 0x8a, 0x9d, 0x11, 0x17, 0x7b, 0x3c, 0x2b, 0xda, 0xb2, 0x38, 0x88, 0x6a, 0x7e, 0x12, 0x06,
	0x3f, 0x11, 0xa8, 0x01, 0xde, 0x41, 0xde, 0x4b, 0xed, 0xd7, 0xc2, 0x69, 0x20, 0xfd, 0x5d, 0x73,
	0x9e, 0x87, 0xe9, 0xa1, 0xad, 0x1a, 0x94, 0x69, 0xbc, 0xc9, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x13, 0x9c, 0x1b, 0xa9, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrdersClient is the client API for Orders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdersClient interface {
	CreateOrder(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*OrderInfo, error)
	CommitValidation(ctx context.Context, in *ValidationResult, opts ...grpc.CallOption) (*CommitResult, error)
}

type ordersClient struct {
	cc *grpc.ClientConn
}

func NewOrdersClient(cc *grpc.ClientConn) OrdersClient {
	return &ordersClient{cc}
}

func (c *ordersClient) CreateOrder(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	out := new(OrderInfo)
	err := c.cc.Invoke(ctx, "/pb.Orders/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) CommitValidation(ctx context.Context, in *ValidationResult, opts ...grpc.CallOption) (*CommitResult, error) {
	out := new(CommitResult)
	err := c.cc.Invoke(ctx, "/pb.Orders/CommitValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersServer is the server API for Orders service.
type OrdersServer interface {
	CreateOrder(context.Context, *WorkRequest) (*OrderInfo, error)
	CommitValidation(context.Context, *ValidationResult) (*CommitResult, error)
}

func RegisterOrdersServer(s *grpc.Server, srv OrdersServer) {
	s.RegisterService(&_Orders_serviceDesc, srv)
}

func _Orders_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Orders/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).CreateOrder(ctx, req.(*WorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_CommitValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).CommitValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Orders/CommitValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).CommitValidation(ctx, req.(*ValidationResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Orders",
	HandlerType: (*OrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Orders_CreateOrder_Handler,
		},
		{
			MethodName: "CommitValidation",
			Handler:    _Orders_CommitValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orders.proto",
}
