// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkRequest struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Add                  int32    `protobuf:"varint,2,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkRequest) Reset()         { *m = WorkRequest{} }
func (m *WorkRequest) String() string { return proto.CompactTextString(m) }
func (*WorkRequest) ProtoMessage()    {}
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *WorkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkRequest.Unmarshal(m, b)
}
func (m *WorkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkRequest.Marshal(b, m, deterministic)
}
func (m *WorkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkRequest.Merge(m, src)
}
func (m *WorkRequest) XXX_Size() int {
	return xxx_messageInfo_WorkRequest.Size(m)
}
func (m *WorkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkRequest proto.InternalMessageInfo

func (m *WorkRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *WorkRequest) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

type OrderInfo struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	DatabaseMarkleRoot   string   `protobuf:"bytes,2,opt,name=database_markle_root,json=databaseMarkleRoot,proto3" json:"database_markle_root,omitempty"`
	ScriptMarkleRoot     string   `protobuf:"bytes,3,opt,name=script_markle_root,json=scriptMarkleRoot,proto3" json:"script_markle_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *OrderInfo) GetDatabaseMarkleRoot() string {
	if m != nil {
		return m.DatabaseMarkleRoot
	}
	return ""
}

func (m *OrderInfo) GetScriptMarkleRoot() string {
	if m != nil {
		return m.ScriptMarkleRoot
	}
	return ""
}

type ValidationResult struct {
	DatabaseMarkleRoot   string   `protobuf:"bytes,1,opt,name=database_markle_root,json=databaseMarkleRoot,proto3" json:"database_markle_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResult) Reset()         { *m = ValidationResult{} }
func (m *ValidationResult) String() string { return proto.CompactTextString(m) }
func (*ValidationResult) ProtoMessage()    {}
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *ValidationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResult.Unmarshal(m, b)
}
func (m *ValidationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResult.Marshal(b, m, deterministic)
}
func (m *ValidationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResult.Merge(m, src)
}
func (m *ValidationResult) XXX_Size() int {
	return xxx_messageInfo_ValidationResult.Size(m)
}
func (m *ValidationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResult proto.InternalMessageInfo

func (m *ValidationResult) GetDatabaseMarkleRoot() string {
	if m != nil {
		return m.DatabaseMarkleRoot
	}
	return ""
}

type CommitResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitResult) Reset()         { *m = CommitResult{} }
func (m *CommitResult) String() string { return proto.CompactTextString(m) }
func (*CommitResult) ProtoMessage()    {}
func (*CommitResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *CommitResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResult.Unmarshal(m, b)
}
func (m *CommitResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResult.Marshal(b, m, deterministic)
}
func (m *CommitResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResult.Merge(m, src)
}
func (m *CommitResult) XXX_Size() int {
	return xxx_messageInfo_CommitResult.Size(m)
}
func (m *CommitResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WorkRequest)(nil), "pb.WorkRequest")
	proto.RegisterType((*OrderInfo)(nil), "pb.OrderInfo")
	proto.RegisterType((*ValidationResult)(nil), "pb.ValidationResult")
	proto.RegisterType((*CommitResult)(nil), "pb.CommitResult")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x6d, 0xda, 0xaf, 0x95, 0x72, 0xf9, 0x80, 0xe8, 0x54, 0xa1, 0xaa, 0x53, 0xe5, 0xa9, 0x03,
	0x0a, 0x08, 0x06, 0x16, 0xb6, 0xb2, 0x30, 0x20, 0x24, 0x0f, 0x30, 0x56, 0x0e, 0x36, 0x52, 0xd4,
	0xa4, 0x17, 0xce, 0x17, 0x56, 0xfe, 0x3a, 0xb2, 0x53, 0x68, 0x41, 0xea, 0x76, 0x77, 0xef, 0xf9,
	0xbd, 0xf3, 0x3b, 0xc8, 0x88, 0xad, 0xe3, 0xa2, 0x65, 0x12, 0xc2, 0x61, 0x5b, 0xaa, 0x5b, 0xc8,
	0x5e, 0x88, 0x37, 0xda, 0xbd, 0x77, 0xce, 0x0b, 0x9e, 0xc3, 0xa4, 0xf3, 0x8e, 0x2b, 0x3b, 0x4b,
	0x16, 0xc9, 0x32, 0xd5, 0xbb, 0x0e, 0x73, 0x18, 0x19, 0x6b, 0x67, 0xc3, 0x45, 0xb2, 0x1c, 0xeb,
	0x50, 0xaa, 0x4f, 0x48, 0x9f, 0x82, 0xd6, 0xc3, 0xf6, 0x8d, 0x10, 0xe1, 0x9f, 0xb1, 0x96, 0x77,
	0x8f, 0x62, 0x8d, 0x57, 0x30, 0xb5, 0x46, 0x4c, 0x69, 0xbc, 0x5b, 0x37, 0x86, 0x37, 0xb5, 0x5b,
	0x33, 0x91, 0x44, 0x8d, 0x54, 0xe3, 0x37, 0xf6, 0x18, 0x21, 0x4d, 0x24, 0x78, 0x01, 0xe8, 0x5f,
	0xb9, 0x6a, 0xe5, 0x17, 0x7f, 0x14, 0xf9, 0x79, 0x8f, 0xec, 0xd9, 0xea, 0x1e, 0xf2, 0x67, 0x53,
	0x57, 0xd6, 0x48, 0x45, 0x5b, 0xed, 0x7c, 0x57, 0xcb, 0x51, 0xcf, 0xe4, 0x98, 0xa7, 0x3a, 0x85,
	0xff, 0x2b, 0x6a, 0x9a, 0x4a, 0x7a, 0x85, 0xeb, 0x0f, 0x18, 0xc7, 0x6f, 0xe1, 0x25, 0x64, 0x2b,
	0x76, 0x46, 0x5c, 0xdf, 0x9e, 0x15, 0x6d, 0x59, 0x1c, 0x24, 0x35, 0x3f, 0x09, 0x83, 0x9f, 0x04,
	0xd4, 0x00, 0xef, 0x20, 0xef, 0x95, 0xf6, 0x5b, 0xe1, 0x34, 0x90, 0xfe, 0x6e, 0x39, 0xcf, 0xc3,
	0xf4, 0xd0, 0x55, 0x0d, 0xca, 0x49, 0x3c, 0xc9, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc,
	0x27, 0xe2, 0x02, 0xa1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	CreateOrder(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*OrderInfo, error)
	CommitValidation(ctx context.Context, in *ValidationResult, opts ...grpc.CallOption) (*CommitResult, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateOrder(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	out := new(OrderInfo)
	err := c.cc.Invoke(ctx, "/pb.Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CommitValidation(ctx context.Context, in *ValidationResult, opts ...grpc.CallOption) (*CommitResult, error) {
	out := new(CommitResult)
	err := c.cc.Invoke(ctx, "/pb.Order/CommitValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	CreateOrder(context.Context, *WorkRequest) (*OrderInfo, error)
	CommitValidation(context.Context, *ValidationResult) (*CommitResult, error)
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*WorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CommitValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CommitValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Order/CommitValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CommitValidation(ctx, req.(*ValidationResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "CommitValidation",
			Handler:    _Order_CommitValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
