// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datapool.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatapoolId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatapoolId) Reset()         { *m = DatapoolId{} }
func (m *DatapoolId) String() string { return proto.CompactTextString(m) }
func (*DatapoolId) ProtoMessage()    {}
func (*DatapoolId) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{0}
}

func (m *DatapoolId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatapoolId.Unmarshal(m, b)
}
func (m *DatapoolId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatapoolId.Marshal(b, m, deterministic)
}
func (m *DatapoolId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatapoolId.Merge(m, src)
}
func (m *DatapoolId) XXX_Size() int {
	return xxx_messageInfo_DatapoolId.Size(m)
}
func (m *DatapoolId) XXX_DiscardUnknown() {
	xxx_messageInfo_DatapoolId.DiscardUnknown(m)
}

var xxx_messageInfo_DatapoolId proto.InternalMessageInfo

func (m *DatapoolId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DatapoolContent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 int32    `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatapoolContent) Reset()         { *m = DatapoolContent{} }
func (m *DatapoolContent) String() string { return proto.CompactTextString(m) }
func (*DatapoolContent) ProtoMessage()    {}
func (*DatapoolContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{1}
}

func (m *DatapoolContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatapoolContent.Unmarshal(m, b)
}
func (m *DatapoolContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatapoolContent.Marshal(b, m, deterministic)
}
func (m *DatapoolContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatapoolContent.Merge(m, src)
}
func (m *DatapoolContent) XXX_Size() int {
	return xxx_messageInfo_DatapoolContent.Size(m)
}
func (m *DatapoolContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DatapoolContent.DiscardUnknown(m)
}

var xxx_messageInfo_DatapoolContent proto.InternalMessageInfo

func (m *DatapoolContent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DatapoolContent) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type UpdateResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResult) Reset()         { *m = UpdateResult{} }
func (m *UpdateResult) String() string { return proto.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()    {}
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{2}
}

func (m *UpdateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResult.Unmarshal(m, b)
}
func (m *UpdateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResult.Marshal(b, m, deterministic)
}
func (m *UpdateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResult.Merge(m, src)
}
func (m *UpdateResult) XXX_Size() int {
	return xxx_messageInfo_UpdateResult.Size(m)
}
func (m *UpdateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResult proto.InternalMessageInfo

type CreateResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResult) Reset()         { *m = CreateResult{} }
func (m *CreateResult) String() string { return proto.CompactTextString(m) }
func (*CreateResult) ProtoMessage()    {}
func (*CreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{3}
}

func (m *CreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResult.Unmarshal(m, b)
}
func (m *CreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResult.Marshal(b, m, deterministic)
}
func (m *CreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResult.Merge(m, src)
}
func (m *CreateResult) XXX_Size() int {
	return xxx_messageInfo_CreateResult.Size(m)
}
func (m *CreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResult proto.InternalMessageInfo

type DeleteResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResult) Reset()         { *m = DeleteResult{} }
func (m *DeleteResult) String() string { return proto.CompactTextString(m) }
func (*DeleteResult) ProtoMessage()    {}
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1730072fb3ac63c1, []int{4}
}

func (m *DeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResult.Unmarshal(m, b)
}
func (m *DeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResult.Marshal(b, m, deterministic)
}
func (m *DeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResult.Merge(m, src)
}
func (m *DeleteResult) XXX_Size() int {
	return xxx_messageInfo_DeleteResult.Size(m)
}
func (m *DeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DatapoolId)(nil), "pb.DatapoolId")
	proto.RegisterType((*DatapoolContent)(nil), "pb.DatapoolContent")
	proto.RegisterType((*UpdateResult)(nil), "pb.UpdateResult")
	proto.RegisterType((*CreateResult)(nil), "pb.CreateResult")
	proto.RegisterType((*DeleteResult)(nil), "pb.DeleteResult")
}

func init() { proto.RegisterFile("datapool.proto", fileDescriptor_1730072fb3ac63c1) }

var fileDescriptor_1730072fb3ac63c1 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x49, 0x2c, 0x49,
	0x2c, 0xc8, 0xcf, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92,
	0xe1, 0xe2, 0x72, 0x81, 0x8a, 0x7a, 0xa6, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x28, 0x99, 0x72, 0xf1, 0xc3, 0x64, 0x9d, 0xf3, 0xf3,
	0x4a, 0x52, 0xf3, 0x4a, 0xd0, 0x95, 0x08, 0x09, 0x71, 0xb1, 0x80, 0x8c, 0x95, 0x60, 0x52, 0x60,
	0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x95, 0xf8, 0xb8, 0x78, 0x42, 0x0b, 0x52, 0x12, 0x4b, 0x52, 0x83,
	0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x40, 0x7c, 0xe7, 0xa2, 0x54, 0x14, 0xbe, 0x4b, 0x6a, 0x4e, 0x2a,
	0x8c, 0x6f, 0xf4, 0x86, 0x91, 0x8b, 0x03, 0x66, 0x8f, 0x90, 0x09, 0x17, 0xb7, 0x7b, 0x6a, 0x09,
	0x9c, 0xcb, 0xa7, 0x57, 0x90, 0xa4, 0x87, 0x70, 0xa2, 0x94, 0x30, 0x32, 0x1f, 0xea, 0x28, 0x25,
	0x06, 0x21, 0x4b, 0x2e, 0x3e, 0x88, 0x95, 0x70, 0x8d, 0xd8, 0x14, 0x4a, 0x09, 0x80, 0x04, 0x51,
	0xdc, 0x06, 0xd6, 0x0a, 0x71, 0x1d, 0x11, 0x5a, 0x51, 0xbc, 0xc1, 0x20, 0x64, 0xc2, 0xc5, 0x07,
	0xf1, 0x08, 0x4e, 0xe7, 0x82, 0x75, 0x21, 0x7b, 0x56, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0xfc, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x35, 0x00, 0x75, 0x90, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatapoolClient is the client API for Datapool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatapoolClient interface {
	GetDatapool(ctx context.Context, in *DatapoolId, opts ...grpc.CallOption) (*DatapoolContent, error)
	UpdateDatapool(ctx context.Context, in *DatapoolContent, opts ...grpc.CallOption) (*UpdateResult, error)
	CreateDatapool(ctx context.Context, in *DatapoolContent, opts ...grpc.CallOption) (*CreateResult, error)
	DeleteDatapool(ctx context.Context, in *DatapoolId, opts ...grpc.CallOption) (*DeleteResult, error)
}

type datapoolClient struct {
	cc *grpc.ClientConn
}

func NewDatapoolClient(cc *grpc.ClientConn) DatapoolClient {
	return &datapoolClient{cc}
}

func (c *datapoolClient) GetDatapool(ctx context.Context, in *DatapoolId, opts ...grpc.CallOption) (*DatapoolContent, error) {
	out := new(DatapoolContent)
	err := c.cc.Invoke(ctx, "/pb.Datapool/GetDatapool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datapoolClient) UpdateDatapool(ctx context.Context, in *DatapoolContent, opts ...grpc.CallOption) (*UpdateResult, error) {
	out := new(UpdateResult)
	err := c.cc.Invoke(ctx, "/pb.Datapool/UpdateDatapool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datapoolClient) CreateDatapool(ctx context.Context, in *DatapoolContent, opts ...grpc.CallOption) (*CreateResult, error) {
	out := new(CreateResult)
	err := c.cc.Invoke(ctx, "/pb.Datapool/CreateDatapool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datapoolClient) DeleteDatapool(ctx context.Context, in *DatapoolId, opts ...grpc.CallOption) (*DeleteResult, error) {
	out := new(DeleteResult)
	err := c.cc.Invoke(ctx, "/pb.Datapool/DeleteDatapool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatapoolServer is the server API for Datapool service.
type DatapoolServer interface {
	GetDatapool(context.Context, *DatapoolId) (*DatapoolContent, error)
	UpdateDatapool(context.Context, *DatapoolContent) (*UpdateResult, error)
	CreateDatapool(context.Context, *DatapoolContent) (*CreateResult, error)
	DeleteDatapool(context.Context, *DatapoolId) (*DeleteResult, error)
}

func RegisterDatapoolServer(s *grpc.Server, srv DatapoolServer) {
	s.RegisterService(&_Datapool_serviceDesc, srv)
}

func _Datapool_GetDatapool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatapoolId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapoolServer).GetDatapool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Datapool/GetDatapool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapoolServer).GetDatapool(ctx, req.(*DatapoolId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datapool_UpdateDatapool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatapoolContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapoolServer).UpdateDatapool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Datapool/UpdateDatapool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapoolServer).UpdateDatapool(ctx, req.(*DatapoolContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datapool_CreateDatapool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatapoolContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapoolServer).CreateDatapool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Datapool/CreateDatapool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapoolServer).CreateDatapool(ctx, req.(*DatapoolContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datapool_DeleteDatapool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatapoolId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatapoolServer).DeleteDatapool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Datapool/DeleteDatapool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatapoolServer).DeleteDatapool(ctx, req.(*DatapoolId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Datapool_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Datapool",
	HandlerType: (*DatapoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDatapool",
			Handler:    _Datapool_GetDatapool_Handler,
		},
		{
			MethodName: "UpdateDatapool",
			Handler:    _Datapool_UpdateDatapool_Handler,
		},
		{
			MethodName: "CreateDatapool",
			Handler:    _Datapool_CreateDatapool_Handler,
		},
		{
			MethodName: "DeleteDatapool",
			Handler:    _Datapool_DeleteDatapool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datapool.proto",
}
