// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidatableCodeRequest struct {
	Bridgeid             string   `protobuf:"bytes,1,opt,name=bridgeid,proto3" json:"bridgeid,omitempty"`
	Datapoolid           string   `protobuf:"bytes,2,opt,name=datapoolid,proto3" json:"datapoolid,omitempty"`
	Add                  int32    `protobuf:"varint,3,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatableCodeRequest) Reset()         { *m = ValidatableCodeRequest{} }
func (m *ValidatableCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ValidatableCodeRequest) ProtoMessage()    {}
func (*ValidatableCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0}
}

func (m *ValidatableCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatableCodeRequest.Unmarshal(m, b)
}
func (m *ValidatableCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatableCodeRequest.Marshal(b, m, deterministic)
}
func (m *ValidatableCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatableCodeRequest.Merge(m, src)
}
func (m *ValidatableCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ValidatableCodeRequest.Size(m)
}
func (m *ValidatableCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatableCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatableCodeRequest proto.InternalMessageInfo

func (m *ValidatableCodeRequest) GetBridgeid() string {
	if m != nil {
		return m.Bridgeid
	}
	return ""
}

func (m *ValidatableCodeRequest) GetDatapoolid() string {
	if m != nil {
		return m.Datapoolid
	}
	return ""
}

func (m *ValidatableCodeRequest) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

type ValidatableCode struct {
	Data                  int32    `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	Add                   int32    `protobuf:"varint,2,opt,name=add,proto3" json:"add,omitempty"`
	Reputation            int32    `protobuf:"varint,3,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Threshould            float32  `protobuf:"fixed32,4,opt,name=threshould,proto3" json:"threshould,omitempty"`
	Resetrate             float32  `protobuf:"fixed32,5,opt,name=resetrate,proto3" json:"resetrate,omitempty"`
	FirstNodeIsfault      bool     `protobuf:"varint,6,opt,name=firstNodeIsfault,proto3" json:"firstNodeIsfault,omitempty"`
	FaultyFraction        float64  `protobuf:"fixed64,7,opt,name=faultyFraction,proto3" json:"faultyFraction,omitempty"`
	Version               int64    `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CountUnstabotagable   int32    `protobuf:"varint,9,opt,name=countUnstabotagable,proto3" json:"countUnstabotagable,omitempty"`
	GoodValidatorDetected bool     `protobuf:"varint,10,opt,name=goodValidatorDetected,proto3" json:"goodValidatorDetected,omitempty"`
	Badreputations        []int32  `protobuf:"varint,11,rep,packed,name=badreputations,proto3" json:"badreputations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ValidatableCode) Reset()         { *m = ValidatableCode{} }
func (m *ValidatableCode) String() string { return proto.CompactTextString(m) }
func (*ValidatableCode) ProtoMessage()    {}
func (*ValidatableCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{1}
}

func (m *ValidatableCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatableCode.Unmarshal(m, b)
}
func (m *ValidatableCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatableCode.Marshal(b, m, deterministic)
}
func (m *ValidatableCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatableCode.Merge(m, src)
}
func (m *ValidatableCode) XXX_Size() int {
	return xxx_messageInfo_ValidatableCode.Size(m)
}
func (m *ValidatableCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatableCode.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatableCode proto.InternalMessageInfo

func (m *ValidatableCode) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *ValidatableCode) GetAdd() int32 {
	if m != nil {
		return m.Add
	}
	return 0
}

func (m *ValidatableCode) GetReputation() int32 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

func (m *ValidatableCode) GetThreshould() float32 {
	if m != nil {
		return m.Threshould
	}
	return 0
}

func (m *ValidatableCode) GetResetrate() float32 {
	if m != nil {
		return m.Resetrate
	}
	return 0
}

func (m *ValidatableCode) GetFirstNodeIsfault() bool {
	if m != nil {
		return m.FirstNodeIsfault
	}
	return false
}

func (m *ValidatableCode) GetFaultyFraction() float64 {
	if m != nil {
		return m.FaultyFraction
	}
	return 0
}

func (m *ValidatableCode) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ValidatableCode) GetCountUnstabotagable() int32 {
	if m != nil {
		return m.CountUnstabotagable
	}
	return 0
}

func (m *ValidatableCode) GetGoodValidatorDetected() bool {
	if m != nil {
		return m.GoodValidatorDetected
	}
	return false
}

func (m *ValidatableCode) GetBadreputations() []int32 {
	if m != nil {
		return m.Badreputations
	}
	return nil
}

type ValidationResult struct {
	Pool                 int32    `protobuf:"varint,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Reject               bool     `protobuf:"varint,2,opt,name=reject,proto3" json:"reject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResult) Reset()         { *m = ValidationResult{} }
func (m *ValidationResult) String() string { return proto.CompactTextString(m) }
func (*ValidationResult) ProtoMessage()    {}
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{2}
}

func (m *ValidationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResult.Unmarshal(m, b)
}
func (m *ValidationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResult.Marshal(b, m, deterministic)
}
func (m *ValidationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResult.Merge(m, src)
}
func (m *ValidationResult) XXX_Size() int {
	return xxx_messageInfo_ValidationResult.Size(m)
}
func (m *ValidationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResult proto.InternalMessageInfo

func (m *ValidationResult) GetPool() int32 {
	if m != nil {
		return m.Pool
	}
	return 0
}

func (m *ValidationResult) GetReject() bool {
	if m != nil {
		return m.Reject
	}
	return false
}

func init() {
	proto.RegisterType((*ValidatableCodeRequest)(nil), "pb.ValidatableCodeRequest")
	proto.RegisterType((*ValidatableCode)(nil), "pb.ValidatableCode")
	proto.RegisterType((*ValidationResult)(nil), "pb.ValidationResult")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_e4ff6184b07e587a) }

var fileDescriptor_e4ff6184b07e587a = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x5d, 0x37, 0x6d, 0xb7, 0x1d, 0x10, 0x5b, 0xcd, 0xc2, 0xca, 0xaa, 0x10, 0x8a, 0x72, 0x40,
	0x11, 0x87, 0x0a, 0x01, 0xe7, 0xbd, 0x80, 0x58, 0x71, 0x01, 0xc9, 0x12, 0x70, 0x76, 0xe2, 0x69,
	0x37, 0x10, 0xc5, 0xc1, 0x9e, 0x80, 0xf8, 0x0c, 0xc4, 0x0f, 0x23, 0x5b, 0x69, 0x1b, 0x85, 0xdc,
	0x66, 0xde, 0xf3, 0xbc, 0x19, 0xcf, 0x3c, 0x78, 0xf8, 0xcb, 0xba, 0xef, 0xe4, 0x76, 0xad, 0xb3,
	0x6c, 0x71, 0xd6, 0x16, 0xd9, 0x1e, 0x6e, 0xbe, 0xe8, 0xba, 0x32, 0x9a, 0x75, 0x51, 0xd3, 0x5b,
	0x6b, 0x48, 0xd1, 0x8f, 0x8e, 0x3c, 0xe3, 0x16, 0x56, 0x85, 0xab, 0xcc, 0x81, 0x2a, 0x23, 0x45,
	0x2a, 0xf2, 0xb5, 0x3a, 0xe5, 0xf8, 0x0c, 0x20, 0x54, 0xb4, 0xd6, 0xd6, 0x95, 0x91, 0xb3, 0xc8,
	0x0e, 0x10, 0xdc, 0x40, 0xa2, 0x8d, 0x91, 0x49, 0x2a, 0xf2, 0x85, 0x0a, 0x61, 0xf6, 0x37, 0x81,
	0xab, 0x51, 0x23, 0x44, 0x98, 0x87, 0x34, 0xaa, 0x2f, 0x54, 0x8c, 0x8f, 0x95, 0xb3, 0x53, 0x65,
	0xe8, 0xe5, 0xa8, 0xed, 0x58, 0x73, 0x65, 0x9b, 0x5e, 0x72, 0x80, 0x04, 0x9e, 0xef, 0x1d, 0xf9,
	0x7b, 0xdb, 0xd5, 0x46, 0xce, 0x53, 0x91, 0xcf, 0xd4, 0x00, 0xc1, 0xa7, 0xb0, 0x76, 0xe4, 0x89,
	0x9d, 0x66, 0x92, 0x8b, 0x48, 0x9f, 0x01, 0x7c, 0x01, 0x9b, 0x7d, 0xe5, 0x3c, 0x7f, 0xb4, 0x86,
	0x3e, 0xf8, 0xbd, 0xee, 0x6a, 0x96, 0xcb, 0x54, 0xe4, 0x2b, 0xf5, 0x1f, 0x8e, 0xcf, 0xe1, 0x51,
	0x0c, 0x7e, 0xbf, 0x77, 0xba, 0x8c, 0xd3, 0x5c, 0xa6, 0x22, 0x17, 0x6a, 0x84, 0xa2, 0x84, 0xcb,
	0x9f, 0xe4, 0x7c, 0x78, 0xb0, 0x4a, 0x45, 0x9e, 0xa8, 0x63, 0x8a, 0x2f, 0xe1, 0xba, 0xb4, 0x5d,
	0xc3, 0x9f, 0x1b, 0xcf, 0xba, 0xb0, 0xac, 0x0f, 0x61, 0x19, 0x72, 0x1d, 0x3f, 0x35, 0x45, 0xe1,
	0x1b, 0x78, 0x72, 0xb0, 0xd6, 0xf4, 0xab, 0xb3, 0xee, 0x1d, 0x31, 0x95, 0x4c, 0x46, 0x42, 0x1c,
	0x72, 0x9a, 0x0c, 0x93, 0x16, 0xda, 0x9c, 0x97, 0xe4, 0xe5, 0x83, 0x34, 0xc9, 0x17, 0x6a, 0x84,
	0x66, 0xb7, 0xb0, 0xe9, 0x8b, 0x2b, 0xdb, 0x28, 0xf2, 0xe1, 0x97, 0x08, 0xf3, 0x70, 0xc5, 0xe3,
	0x55, 0x42, 0x8c, 0x37, 0xb0, 0x74, 0xf4, 0x8d, 0x4a, 0x8e, 0x87, 0x59, 0xa9, 0x3e, 0x7b, 0xf5,
	0x47, 0xc0, 0xf2, 0x6b, 0xb4, 0x14, 0xde, 0xc2, 0xd5, 0x27, 0x67, 0xc8, 0x9d, 0xf5, 0xf0, 0x7a,
	0xd7, 0x16, 0xbb, 0xd1, 0xd1, 0xb7, 0x8f, 0x07, 0xe0, 0xa9, 0x69, 0x76, 0x81, 0x77, 0x80, 0x77,
	0xc4, 0x63, 0x8b, 0x6c, 0x27, 0x24, 0x7a, 0x83, 0x6e, 0xa7, 0xe4, 0xb3, 0x8b, 0x62, 0x19, 0xcd,
	0xfd, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x75, 0xf0, 0x08, 0xec, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	OrderValidation(ctx context.Context, in *ValidatableCode, opts ...grpc.CallOption) (*ValidationResult, error)
	GetValidatableCode(ctx context.Context, in *ValidatableCodeRequest, opts ...grpc.CallOption) (*ValidatableCode, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) OrderValidation(ctx context.Context, in *ValidatableCode, opts ...grpc.CallOption) (*ValidationResult, error) {
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, "/pb.Worker/OrderValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetValidatableCode(ctx context.Context, in *ValidatableCodeRequest, opts ...grpc.CallOption) (*ValidatableCode, error) {
	out := new(ValidatableCode)
	err := c.cc.Invoke(ctx, "/pb.Worker/GetValidatableCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	OrderValidation(context.Context, *ValidatableCode) (*ValidationResult, error)
	GetValidatableCode(context.Context, *ValidatableCodeRequest) (*ValidatableCode, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_OrderValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatableCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).OrderValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Worker/OrderValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).OrderValidation(ctx, req.(*ValidatableCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetValidatableCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatableCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetValidatableCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Worker/GetValidatableCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetValidatableCode(ctx, req.(*ValidatableCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderValidation",
			Handler:    _Worker_OrderValidation_Handler,
		},
		{
			MethodName: "GetValidatableCode",
			Handler:    _Worker_GetValidatableCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
